/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.purchaseRequest;

import enums.ApprovalStatus;
import enums.OrganizationType;
import interfaces.IDataRefreshCallback;
import interfaces.IDataRefreshCallbackAware;
import model.procurement.PurchaseRequest;
import model.user.UserAccount;
import model.workqueue.WorkRequest;
import model.workqueue.WorkflowStep;
import util.CommonUtil;
import util.NavigationUtil;
import util.UIUtil;

import javax.swing.*;
import java.util.List;
import java.util.Map;

/**
 *
 * @author tisaac
 */
public class ProcessPurchaseRequestPanel extends javax.swing.JPanel {

    private PurchaseRequest pr;
    private IDataRefreshCallback callback;
    /**
     * Creates new form ProcessPurchaseRequestPanel
     */
    public ProcessPurchaseRequestPanel(PurchaseRequest pr, IDataRefreshCallback callback) {
        initComponents();
        this.pr = pr;
        this.callback = callback;

        setupListeners();
        UIUtil.clearTable(tblPurchaseItems);
        renderPRBasicInfo();
        renderPurchaseItemTable();
        renderProgressTracking();
    }

    private void setupListeners() {
        btnBack.addActionListener(e -> {
            NavigationUtil.getInstance().goBack();
            callback.refreshData();
        });
    }

    public void renderPRBasicInfo() {
        UIUtil.setLabelText(Map.of(
                lbPRId,  appendWithLabelPrefix(lbPRId, pr.getId()),
                lbRequestDate, appendWithLabelPrefix(lbRequestDate, pr.getRequestDate().toString()),
                lbPRStatus, appendWithLabelPrefix(lbPRStatus, pr.getStatus().name())
        ));
    }

    public void renderPurchaseItemTable() {
        UIUtil.reloadTable(tblPurchaseItems, pr.getPurchaseItems().getPurchaseItemList(),
                e -> new Object[] {
                        e,
                        e.getQuantity(),
                        e.getUnitPrice()
                });
    }

    public static String appendWithLabelPrefix(JLabel label, String value) {
        return label.getText() + value;
    }

    private void renderProgressTracking() {
        List<WorkflowStep> workflowSteps = pr.getWorkflowSteps();
        UserAccount sender = pr.getSender();

        workflowSteps.stream()
                .filter(s -> s.getAssignedUser() != null)
                .forEach(s -> {
                    switch (s.getStepType()) {
                        case REQUESTOR -> {
                            lbRequestorName.setText(CommonUtil.formatOrgAndUser(s));
                            lbRequestorStatus.setText(s.convertStatus());
                        }

                        case APPROVER -> {
                            switch (s.getOrganizationType()) {
                                case IT -> {
                                    lbITName.setText(CommonUtil.formatOrgAndUser(s));
                                    lbITStatus.setText(s.convertStatus());
                                }
                                case PROCUREMENT -> {
                                    lbProcurementName.setText(CommonUtil.formatOrgAndUser(s));
                                    lbProcurementStatus.setText(s.convertStatus());
                                }
                                default -> {
                                    System.out.println("Unknown organization type: " + s.getOrganizationType());
                                }
                            }
                        }
                    }
                });
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPurchaseItems = new javax.swing.JTable();
        lbTitle = new javax.swing.JLabel();
        lbPRId = new javax.swing.JLabel();
        lbRequestDate = new javax.swing.JLabel();
        lbPRStatus = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbTrackingTitle = new javax.swing.JLabel();
        lbRequestorName = new javax.swing.JLabel();
        lbITName = new javax.swing.JLabel();
        lbProcurementName = new javax.swing.JLabel();
        lbRequestorStatus = new javax.swing.JLabel();
        lbITStatus = new javax.swing.JLabel();
        lbProcurementStatus = new javax.swing.JLabel();
        lbNote = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        tblPurchaseItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Quantity", "Unit Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPurchaseItems);

        lbTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Purchase Request Tracking");

        lbPRId.setText("ID:");

        lbRequestDate.setText("Request Date:");

        lbPRStatus.setText("Request Status:");

        lbTrackingTitle.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lbTrackingTitle.setText("Progress Tracking");

        lbRequestorName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbRequestorName.setText("Requestor");

        lbITName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbITName.setText("IT");

        lbProcurementName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbProcurementName.setText("Procurement");

        lbRequestorStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbRequestorStatus.setText("Requestor Status");

        lbITStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbITStatus.setText("Pending...");

        lbProcurementStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbProcurementStatus.setText("Pending...");

        lbNote.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        lbNote.setForeground(new java.awt.Color(255, 0, 0));
        lbNote.setText("Approve means processing, Wait for Completed");

        btnBack.setText("<<Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPRId)
                            .addComponent(lbRequestDate)
                            .addComponent(lbPRStatus)
                            .addComponent(lbNote, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRequestorName)
                    .addComponent(lbITName)
                    .addComponent(lbProcurementName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbRequestorStatus)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbProcurementStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbITStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTrackingTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbPRId)
                        .addGap(18, 18, 18)
                        .addComponent(lbRequestDate)
                        .addGap(18, 18, 18)
                        .addComponent(lbPRStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbNote)
                        .addGap(46, 46, 46)))
                .addComponent(lbTrackingTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRequestorName)
                    .addComponent(lbRequestorStatus))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbITName)
                    .addComponent(lbITStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProcurementName)
                    .addComponent(lbProcurementStatus))
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbITName;
    private javax.swing.JLabel lbITStatus;
    private javax.swing.JLabel lbNote;
    private javax.swing.JLabel lbPRId;
    private javax.swing.JLabel lbPRStatus;
    private javax.swing.JLabel lbProcurementName;
    private javax.swing.JLabel lbProcurementStatus;
    private javax.swing.JLabel lbRequestDate;
    private javax.swing.JLabel lbRequestorName;
    private javax.swing.JLabel lbRequestorStatus;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTrackingTitle;
    private javax.swing.JTable tblPurchaseItems;
    // End of variables declaration//GEN-END:variables
}
