/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.rfq;

import common.AppContext;
import enums.EnterpriseType;
import interfaces.IDataRefreshCallback;
import interfaces.IDataRefreshCallbackAware;
import model.ecosystem.Enterprise;
import model.quotation.RFQ;
import util.NavigationUtil;
import util.UIUtil;
import view.quotation.SubmitQuotationPanel;

/**
 *
 * @author qiyaochen
 */
public class RFQManagmentPanel extends javax.swing.JPanel implements IDataRefreshCallbackAware {

    private IDataRefreshCallback callback;
    /**
     * Creates new form RFQManagmentPanel
     */
    public RFQManagmentPanel() {
        initComponents();
        setupListeners();

        initUI();
    }

    private void initUI() {
        UIUtil.setEnterpriseTitle(lbTitle, AppContext.getUserEnterprise().getName());
        UIUtil.clearTable(tblRFQ);
        refreshRFQTable();
        toggleButtons(AppContext.getUserEnterprise().getType());
    }

    private void setupListeners() {
        btnBack.addActionListener(e -> handleBackbtn());
        btnView.addActionListener(e -> handleViewbtn());
//      TODO:  btnReject.addActionListener(e -> handleRejctbtn());
        btnCreateQuotation.addActionListener(e -> handleCreateQuotationbtn());
    }

    private void handleBackbtn() {
        NavigationUtil.getInstance().goBack();
        callback.refreshData();
    }

    private void handleViewbtn() {
        UIUtil.getSelectedTableObject(
                tblRFQ,
                0,
                RFQ.class,
                this,
                "Please select a RFQ to view"
        ).ifPresent(rfq -> {
            NavigationUtil.getInstance().showCard(
                    new RFQViewDetailPanel(rfq, () -> refreshRFQTable()),
                    "RFQ Detail"
            );
        });


    }

    private void handleCreateQuotationbtn() {
        UIUtil.getSelectedTableObject(
                tblRFQ,
                0,
                RFQ.class,
                this,
                "Please select a RFQ to view"
        ).ifPresent(rfq -> {
            NavigationUtil.getInstance().showCard(
                    new SubmitQuotationPanel(rfq, () -> refreshRFQTable()),
                    "Submit Quotation"
            );
        });
    }

    private void refreshRFQTable() {
        UIUtil.reloadTable(
                tblRFQ,
                AppContext.getNetwork().getRfqDirectory().getRFQList(),
                e -> new Object[] {
                        e,
                        e.getVendor(),
                        e.getDeadline(),
                        e.getStatus(),
                        e.getQuotationCount()
                }
        );
    }

    private void toggleButtons(EnterpriseType type) {
        if (type == EnterpriseType.BUYER){
            UIUtil.hide(
                    btnCreateQuotation,
                    btnReject
            );
        }
    }


    @Override
    public void setCallback(IDataRefreshCallback callback) {
        this.callback = callback;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRFQ = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnCreateQuotation = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        lbTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("RFQ Service");

        tblRFQ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Vendor", "Deadline", "Status", "Quotation Count"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRFQ);
        if (tblRFQ.getColumnModel().getColumnCount() > 0) {
            tblRFQ.getColumnModel().getColumn(0).setPreferredWidth(160);
            tblRFQ.getColumnModel().getColumn(1).setResizable(false);
            tblRFQ.getColumnModel().getColumn(2).setResizable(false);
            tblRFQ.getColumnModel().getColumn(3).setResizable(false);
            tblRFQ.getColumnModel().getColumn(4).setResizable(false);
            tblRFQ.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        btnBack.setText("<<Back");

        btnView.setText("View Detail");

        btnCreateQuotation.setText("Create Quotataion");

        btnReject.setText("Reject");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnView)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReject))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(595, 595, 595)
                                .addComponent(btnCreateQuotation))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnReject))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnCreateQuotation)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateQuotation;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTable tblRFQ;
    // End of variables declaration//GEN-END:variables
}
