/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import common.NetworkManager;
import common.Result;
import common.Session;
import config.MockDataInitializer;
import directory.EnterpriseDirectory;
import directory.ShipmentDirectories;
import directory.UserAccountDirectory;

import java.util.Date;
import model.delivery.ShipmentDirectory;

import model.ecosystem.Enterprise;
import model.ecosystem.Network;
import model.user.UserAccount;
import service.UserService;
import util.NavigationUtil;
import enums.Role;
import util.UIUtil;
import view.shipping.DeliveryCompanyWorkspacePanel;

/**
 *
 * @author linweihong
 */
public class MainJFrame extends javax.swing.JFrame {

    private UserAccountDirectory userAccountDirectory;
    private ShipmentDirectories shipmentDirectories;
    private EnterpriseDirectory enterpriseDirectory;

    Network selectedNetwork;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setResizable(false);
        setSize(900, 700);

        btnLogout.setEnabled(false);

        Network network = MockDataInitializer.initialize(); // pre-populate data
        NavigationUtil.init(userProcessContainer);

        WelcomePanel wl = new WelcomePanel();
        NavigationUtil.getInstance().showCard(wl, "Welcome");

        // show network list
        generateNetworkList();

        userAccountDirectory = network.getUserAccountDir();
        shipmentDirectories = network.getShipmentDirectories();
        enterpriseDirectory = network.getEnterpriseDir();

        System.out.println("user accounts: " + userAccountDirectory.getUserAccountList());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        txtUserId = new javax.swing.JTextField();
        pwdPwd = new javax.swing.JPasswordField();
        lbUserId = new javax.swing.JLabel();
        lbPwd = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lbNetwork = new javax.swing.JLabel();
        cmbNetwork = new javax.swing.JComboBox<>();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setPreferredSize(new java.awt.Dimension(850, 650));

        MenuPanel.setBackground(new java.awt.Color(102, 102, 102));
        MenuPanel.setPreferredSize(new java.awt.Dimension(850, 80));

        btnLogin.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lbUserId.setBackground(new java.awt.Color(255, 255, 255));
        lbUserId.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lbUserId.setForeground(new java.awt.Color(255, 255, 255));
        lbUserId.setText("UserId");

        lbPwd.setBackground(new java.awt.Color(255, 255, 255));
        lbPwd.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lbPwd.setForeground(new java.awt.Color(255, 255, 255));
        lbPwd.setText("Password");

        btnLogout.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        btnLogout.setText("LogOut");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lbNetwork.setBackground(new java.awt.Color(255, 255, 255));
        lbNetwork.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lbNetwork.setForeground(new java.awt.Color(255, 255, 255));
        lbNetwork.setText("Network");

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
                MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lbNetwork)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbNetwork, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108,
                                        Short.MAX_VALUE)
                                .addComponent(lbUserId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbPwd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pwdPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLogout)
                                .addGap(16, 16, 16)));
        MenuPanelLayout.setVerticalGroup(
                MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MenuPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(
                                        MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(pwdPwd, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lbNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cmbNetwork, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(20, Short.MAX_VALUE)));

        userProcessContainer.setBackground(new java.awt.Color(204, 204, 204));
        userProcessContainer.setForeground(new java.awt.Color(153, 153, 255));
        userProcessContainer.setMinimumSize(new java.awt.Dimension(900, 570));
        userProcessContainer.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                        .addComponent(userProcessContainer, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userProcessContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 570,
                                        Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLoginActionPerformed
        String network = (String) cmbNetwork.getSelectedItem();
        Network selectedNetwork = NetworkManager.findByName(network).orElse(null);

        String username = txtUserId.getText();
        String password = String.valueOf(pwdPwd.getPassword());

        Result<UserAccount> result = UserService.getInstance().login(selectedNetwork, username, password);
        if (!result.isSuccess()) {
            UIUtil.showError(this, result.getMessage());
            return;
        }

        toggleAuthUIState();
        UserAccount user = result.getData();
        Role role = user.getUserType();
        Session.setCurrentNetwork(selectedNetwork);
        Session.setCurrentUser(user);

        switch (role) {
            case SYS_ADMIN -> {
                EcosystemWorkAreaPanel adminWorkspace = new EcosystemWorkAreaPanel();
                NavigationUtil.getInstance().showCard(adminWorkspace, "EcosystemWorkArea");
            }

            case IT_ADMIN -> {
                
            }

            case SHIPPING_COORDINATOR -> {
                // todo: login as UPS, not only FedEx
                Enterprise enterprise = enterpriseDirectory.findEnterpriseByName("FedEx");
                ShipmentDirectory shipmentDirectory = shipmentDirectories.getShipmentDirectory(enterprise);
                NavigationUtil.getInstance().showCard(new DeliveryCompanyWorkspacePanel(shipmentDirectory),"DeliveryCompanyWorkspacePanel");

            }

            default -> {
                DashboardPanel dashboard = new DashboardPanel();
                NavigationUtil.getInstance().showCard(dashboard, "Dashboard");
            }
        }

    }// GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLogoutActionPerformed
        toggleAuthUIState();
        UIUtil.clearPasswordFields(pwdPwd);
        UIUtil.clearTextFields(txtUserId);
        NavigationUtil.getInstance().reset();
        NavigationUtil.getInstance().showCard(new WelcomePanel(), "Welcome");

    }// GEN-LAST:event_btnLogoutActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JComboBox<String> cmbNetwork;
    private javax.swing.JLabel lbNetwork;
    private javax.swing.JLabel lbPwd;
    private javax.swing.JLabel lbUserId;
    private javax.swing.JPasswordField pwdPwd;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    private void toggleAuthUIState() {
        btnLogin.setEnabled(!btnLogin.isEnabled());
        btnLogout.setEnabled(!btnLogout.isEnabled());
        txtUserId.setEnabled(!txtUserId.isEnabled());
        pwdPwd.setEnabled(!pwdPwd.isEnabled());
        cmbNetwork.setEnabled(!cmbNetwork.isEnabled());
    }

    private void generateNetworkList() {
        UIUtil.populateComboBox(
                cmbNetwork,
                NetworkManager.getNetworks(),
                Network::getName,
                "-- Select Network --");
    }
}
