/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.shipping;


import model.delivery.ShipmentDirectory;
import util.NavigationUtil;


/**
 *
 * @author linweihong
 */
public class DeliveryCompanyWorkspacePanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryPanel
     */
    
    ShipmentDirectory shipmentDirectory;
    
    
    public DeliveryCompanyWorkspacePanel(ShipmentDirectory shipmentDirectory) {
        initComponents();
        this.shipmentDirectory = shipmentDirectory;
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewDeliveryReq = new javax.swing.JButton();

        btnBack = new javax.swing.JButton();


        btnViewDeliveryReq.setText("Manage Delivery Requests");
        btnViewDeliveryReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDeliveryReqActionPerformed(evt);
            }
        });


        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()

                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnViewDeliveryReq))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnBack)))

                .addContainerGap(478, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()

                .addGap(53, 53, 53)
                .addComponent(btnBack)
                .addGap(47, 47, 47)

                .addComponent(btnViewDeliveryReq)
                .addContainerGap(349, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDeliveryReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDeliveryReqActionPerformed
        // TODO add your handling code here:
        


        NavigationUtil.getInstance().showCard(new ManageDeliveryReqPanel(shipmentDirectory), "ManageDeliveryReqPanel");

        
        
        
        
        
    }//GEN-LAST:event_btnViewDeliveryReqActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        NavigationUtil.getInstance().goBack();
        
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;

    private javax.swing.JButton btnViewDeliveryReq;
    // End of variables declaration//GEN-END:variables
}
