/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.sysAdmin;

import common.NetworkManager;
import enums.EnterpriseType;
import enums.OrganizationType;
import enums.Role;
import model.ecosystem.Ecosystem;
import model.ecosystem.Enterprise;
import model.ecosystem.Network;
import util.NavigationUtil;
import util.UIUtil;

/**
 *
 * @author tisaac
 */
public class EcosystemWorkAreaPanel extends javax.swing.JPanel {

    private Network selectedNetwork;
    /**
     * Creates new form EcosystemWorkAreaPanel
     */
    public EcosystemWorkAreaPanel() {
        initComponents();
        toogleEnterpriseFields(false);
        UIUtil.clearTable(tblNetwork, tblEnterprise);
        reloadNetworkTable();
        setupListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNetwork = new javax.swing.JTable();
        btnCreateNetwork = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        btnCreateEnterprise = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        lbNetwork = new javax.swing.JLabel();
        lbEntName = new javax.swing.JLabel();
        lbEntType = new javax.swing.JLabel();
        cmbEnterpriseType = new javax.swing.JComboBox<>();
        lbUserPwd = new javax.swing.JLabel();
        txtEnterpriseName = new javax.swing.JTextField();
        txtAdminUserName = new javax.swing.JTextField();
        lbUserName = new javax.swing.JLabel();
        pwdAdminUserPwd = new javax.swing.JPasswordField();
        lbEntList = new javax.swing.JLabel();
        lbNetworkList = new javax.swing.JLabel();
        txtNetworkName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(850, 570));

        tblNetwork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Network Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNetwork);
        if (tblNetwork.getColumnModel().getColumnCount() > 0) {
            tblNetwork.getColumnModel().getColumn(0).setResizable(false);
        }

        btnCreateNetwork.setText("Create Network");
        btnCreateNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNetworkActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Ecosystem Management (System Admin page)");

        btnCreateEnterprise.setText("Create Enterprise");
        btnCreateEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEnterpriseActionPerformed(evt);
            }
        });

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Enterprise", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblEnterprise);
        if (tblEnterprise.getColumnModel().getColumnCount() > 0) {
            tblEnterprise.getColumnModel().getColumn(0).setResizable(false);
            tblEnterprise.getColumnModel().getColumn(1).setResizable(false);
        }

        lbNetwork.setText("Network Name");

        lbEntName.setText("Enterprise Name");

        lbEntType.setText("Enterprise Type");

        lbUserPwd.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        lbUserPwd.setText("Admin User Pwd");

        lbUserName.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        lbUserName.setText("Admin User Name");

        lbEntList.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbEntList.setText("Enterprise List");

        lbNetworkList.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbNetworkList.setText("Network List");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Next>>");

        btnView.setText("View All User");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        jLabel2.setText("View user detail under enterprise");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCreateNetwork)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNetwork)
                                .addGap(18, 18, 18)
                                .addComponent(txtNetworkName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                                .addComponent(btnCreateEnterprise))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbEntName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbEntType))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEnterpriseName)
                                            .addComponent(cmbEnterpriseType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbUserName)
                                            .addComponent(lbUserPwd))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAdminUserName)
                                            .addComponent(pwdAdminUserPwd)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(153, 153, 153))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNetworkList)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(52, 52, 52)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnView))
                            .addComponent(lbEntList)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEntName)
                            .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEntType)
                            .addComponent(cmbEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAdminUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbUserName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pwdAdminUserPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbUserPwd))
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateEnterprise))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNetworkName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNetwork))
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateNetwork)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEntList)
                    .addComponent(lbNetworkList)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(jLabel2))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNetworkActionPerformed
        Ecosystem.getInstance().AddNetwork(txtNetworkName.getText());
        UIUtil.reloadTable(tblNetwork, NetworkManager.getNetworks(), n -> new Object[]{
                n.getName()
        });
        UIUtil.clearTextComponents(txtNetworkName);
    }//GEN-LAST:event_btnCreateNetworkActionPerformed

    private void btnCreateEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEnterpriseActionPerformed
        String enterpriseName = txtEnterpriseName.getText();
        String userName = txtAdminUserName.getText();
        String password = new String(pwdAdminUserPwd.getPassword());

        // Convert type to enum
        String entType = cmbEnterpriseType.getSelectedItem().toString();
        EnterpriseType type = UIUtil.getSelectedEnum(cmbEnterpriseType, EnterpriseType.class);

        Enterprise ent = selectedNetwork.getEnterpriseDir().createEnterprise(enterpriseName, type);

        // Create admin user account in IT organization
        selectedNetwork.getUserAccountService().createUserFromOrganization(
                userName,
                password,
                Role.IT_ADMIN,
                selectedNetwork.getOrgService().createOrgFromEnterprise(OrganizationType.IT, ent),
                ent
        );

        // reload Table
        reloadEnterpriseTable();

        // Clear fields
        UIUtil.clearTextComponents(txtAdminUserName, txtEnterpriseName);
        UIUtil.clearPasswordFields(pwdAdminUserPwd);
        UIUtil.resetComboBoxes(cmbEnterpriseType);
        

    }//GEN-LAST:event_btnCreateEnterpriseActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        int selectedRow = tblEnterprise.getSelectedRow();
        if (selectedRow < 0) {
            UIUtil.showInfo(this, "Please select a Enterprise to continue");
            return;
        }
        String enterpriseName = (String) tblEnterprise.getValueAt(selectedRow, 0);
        Enterprise selectedEnterprise = selectedNetwork.getEnterpriseDir().findEnterpriseByName(enterpriseName);

        ViewEnterpriseUserPanel viewEnterpriseUser = new ViewEnterpriseUserPanel(selectedEnterprise);
        NavigationUtil.getInstance().showCard(viewEnterpriseUser, "ViewEnterpriseUser");
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateEnterprise;
    private javax.swing.JButton btnCreateNetwork;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cmbEnterpriseType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbEntList;
    private javax.swing.JLabel lbEntName;
    private javax.swing.JLabel lbEntType;
    private javax.swing.JLabel lbNetwork;
    private javax.swing.JLabel lbNetworkList;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JLabel lbUserPwd;
    private javax.swing.JPasswordField pwdAdminUserPwd;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTable tblNetwork;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtAdminUserName;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JTextField txtNetworkName;
    // End of variables declaration//GEN-END:variables

    private void toogleEnterpriseFields(boolean enable) {
        txtEnterpriseName.setEnabled(enable);
        cmbEnterpriseType.setEnabled(enable);
        txtAdminUserName.setEnabled(enable);
        pwdAdminUserPwd.setEnabled(enable);
        btnCreateEnterprise.setEnabled(enable);
        tblEnterprise.setEnabled(enable);
    }

    private void setupListeners() {
        tblNetwork.getSelectionModel().addListSelectionListener(n -> {
            if (!n.getValueIsAdjusting()) {
                handleNetworkSelection();
            }
        });
    }

    private void handleNetworkSelection() {
        UIUtil.getSelectedTableValue(tblNetwork, 0, this, "Please select a network to continue")
                .ifPresent(v -> {
                    selectedNetwork = NetworkManager.findByName(v).orElse(null);
                    toogleEnterpriseFields(true);
                    UIUtil.populateComboBoxFromEnum(cmbEnterpriseType, EnterpriseType.class, "---Select Type ---");
                    reloadEnterpriseTable();
                });
    }

    private void reloadNetworkTable() {
        UIUtil.reloadTable(tblNetwork, NetworkManager.getNetworks(), n -> new Object[]{
                n.getName()
        });
    }

    private void reloadEnterpriseTable() {
        UIUtil.reloadTable(tblEnterprise,
                selectedNetwork.getEnterpriseDir().getEnterprisesList(),
                e -> new Object[]{ e.getName(), e.getType()
        });
    }
}
