/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.services;

import common.AppContext;
import common.Session;
import enums.Role;
import interfaces.IDataRefreshCallback;
import interfaces.IDataRefreshCallbackAware;
import model.ecosystem.Enterprise;
import model.ecosystem.Network;
import model.ecosystem.Organization;
import model.user.UserAccount;
import util.NavigationUtil;
import util.UIUtil;

/**
 *
 * @author tisaac
 */
public class HRServicePanel extends javax.swing.JPanel implements IDataRefreshCallbackAware {

    private Enterprise enterprise;
    private IDataRefreshCallback callback;
    private Organization selectedOrg;

    /**
     * Creates new form HRServicePanel
     */
    public HRServicePanel() {
        initComponents();

        UserAccount user = AppContext.getUser();
        Network network = AppContext.getNetwork();

        this.enterprise = user.getOrg().getEnterprise();
        if (user == null || enterprise == null || network == null) {
            System.err.println("Session returned null!");
            UIUtil.showError(this, "User not logged in");
            return;
        }

        UIUtil.setEnterpriseTitle(lbTitle, user.getEnterprise().getName());
        UIUtil.clearTable(tblUserAccount);
        setCreateFieldsEnabled(false);
        enterprise = user.getOrg().getEnterprise();
        setupListeners();

        UIUtil.populateComboBox(
                cmbOrg,
                enterprise.getOrganizationDir().getOrganizationList(),
                u -> u.getTypeName().toString(),
                "--Select Organization--"
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        btnCreateUser = new javax.swing.JButton();
        pwdUserPwd = new javax.swing.JPasswordField();
        lbUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lbUserPwd = new javax.swing.JLabel();
        cmbOrg = new javax.swing.JComboBox<>();
        lbOrg = new javax.swing.JLabel();
        lbRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserAccount = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        lbTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("HR Organization");

        btnCreateUser.setText("Create New User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        lbUserName.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        lbUserName.setText("User Name");

        lbUserPwd.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        lbUserPwd.setText("User Pwd");

        cmbOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrgActionPerformed(evt);
            }
        });

        lbOrg.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        lbOrg.setText("Organization");

        lbRole.setText("Role");

        tblUserAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User Id", "User Name", "Organization", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUserAccount);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        jLabel1.setText("Register New Employee");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbUserName)
                                    .addComponent(lbUserPwd)
                                    .addComponent(lbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUserName)
                                    .addComponent(pwdUserPwd)
                                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCreateUser, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbOrg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbUserName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pwdUserPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbUserPwd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbRole))
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateUser)
                        .addGap(149, 149, 149))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBack)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbOrg)
                            .addComponent(cmbOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // store user account
        Network network = AppContext.getNetwork();

        String userName = txtUserName.getText();
        String userPwd = new String(pwdUserPwd.getPassword());
        String role = cmbRole.getSelectedItem().toString();

        network.getUserAccountService().createUserFromOrganization(
                userName,
                userPwd,
                Role.valueOf(role),
                selectedOrg,
                enterprise
        );

        // clear fields
        UIUtil.clearTextComponents(
                txtUserName,
                pwdUserPwd
        );
        UIUtil.resetComboBoxes(cmbRole);
        reloadUserTable();
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void cmbOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrgActionPerformed
        // Load user inside organization
    }//GEN-LAST:event_cmbOrgActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        NavigationUtil.getInstance().goBack();
        callback.refreshData();
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JComboBox<String> cmbOrg;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbOrg;
    private javax.swing.JLabel lbRole;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JLabel lbUserPwd;
    private javax.swing.JPasswordField pwdUserPwd;
    private javax.swing.JTable tblUserAccount;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void setCreateFieldsEnabled(boolean enable) {
        UIUtil.toggleComponentsEnabled(enable,
                txtUserName,
                pwdUserPwd,
                cmbRole,
                btnCreateUser
        );
    }

    private void setupListeners() {
        UIUtil.registerComboBoxListener(cmbOrg, org -> {
            if (org == null || org.equals("--Select Organization--")) {
                setCreateFieldsEnabled(false);
                return;
            }

            // Load all user under this organization
            setCreateFieldsEnabled(true);

            selectedOrg = enterprise.getOrganizationDir().findOrganizationByName(org);
            if (selectedOrg == null) {
                UIUtil.showError(this, "Selected organization not found: " + org);
                return;
            }

            reloadUserTable();

            UIUtil.populateComboBoxFromEnum(
                    cmbRole,
                    Role.class,
                    "--Select Role--"
            );
        });
    }

    private void reloadUserTable() {
        UIUtil.reloadTable(
                tblUserAccount,
                // get all user name under organization
                selectedOrg.getAllUserAccounts(),
                u -> new Object[]{
                        u.getUserId(),
                        u.getUsername(),
                        u.getOrg().getTypeName(),
                        u.getUserType()
                });
    }

    @Override
    public void setCallback(IDataRefreshCallback callback) {
        this.callback = callback;
    }
}
