/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.quotation;

import interfaces.IDataRefreshCallback;
import model.quotation.Quotation;
import model.user.UserAccount;
import model.workqueue.WorkflowStep;
import util.CommonUtil;
import util.NavigationUtil;
import util.UIUtil;

import java.util.List;
import java.util.Map;

/**
 *
 * @author tisaac
 */
public class QuotationViewDetailPanel extends javax.swing.JPanel {

    private Quotation quotation;
    /**
     * Creates new form QuotationViewDetailPanel
     */
    public QuotationViewDetailPanel(Quotation quotation) {
        initComponents();
        this.quotation = quotation;
        loadQuotationDetails();
        setupListener();
        renderProgressTracking();
    }

    private void setupListener() {
        btnBack.addActionListener(e -> {
            NavigationUtil.getInstance().goBack();
        });
    }

    private void loadQuotationDetails() {
        UIUtil.adjustLabelText(lbQuotationId, quotation.getId(), UIUtil.AppendMode.APPEND, "");
        UIUtil.adjustLabelText(lbRFQId, quotation.getLinkedRFQId(), UIUtil.AppendMode.APPEND, "");
        UIUtil.adjustLabelText(lbPrice, String.valueOf(quotation.getPrice()), UIUtil.AppendMode.APPEND, "");
        UIUtil.adjustLabelText(lbTerms, quotation.getTerms(), UIUtil.AppendMode.APPEND, "");
        UIUtil.adjustLabelText(lbRemarks, quotation.getRemarks(), UIUtil.AppendMode.APPEND, "");
    }

    private void renderProgressTracking() {
        List<WorkflowStep> workflowSteps = quotation.getWorkflowSteps();
        UserAccount sender = quotation.getSender();

        workflowSteps.stream()
                .filter(s -> s.getAssignedUser() != null)
                .forEach(s -> {
                    switch (s.getStepType()) {
                        case REQUESTOR -> {
                            lbRequestorName.setText(CommonUtil.formatOrgAndUser(s));
                            lbRequestorStatus.setText(s.convertStatus());
                        }

                        case APPROVER -> {
                            switch (s.getOrganizationType()) {
                                case FINANCE -> {
                                    lbFinanceName.setText(CommonUtil.formatOrgAndUser(s));
                                    lbFinanceStatus.setText(s.convertStatus());
                                }
                                case PROCUREMENT -> {
                                    lbProcurementName.setText(CommonUtil.formatOrgAndUser(s));
                                    lbProcurementStatus.setText(s.convertStatus());
                                }
                                default -> {
                                    System.out.println("Unknown organization type: " + s.getOrganizationType());
                                }
                            }
                        }
                    }
                });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbTerms = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbRemarks = new javax.swing.JLabel();
        lbQuotationId = new javax.swing.JLabel();
        lbRFQId = new javax.swing.JLabel();
        lbRequestorStatus = new javax.swing.JLabel();
        lbProcurementStatus = new javax.swing.JLabel();
        lbFinanceStatus = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbTrackingTitle = new javax.swing.JLabel();
        lbRequestorName = new javax.swing.JLabel();
        lbProcurementName = new javax.swing.JLabel();
        lbFinanceName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        lbTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Quotation Details");

        lbTerms.setText("Terms:");

        lbPrice.setText("Price:");

        lbRemarks.setText("Remarks:");

        lbQuotationId.setText("Quotation ID: ");

        lbRFQId.setText("Linked RFQ ID: ");

        lbRequestorStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbRequestorStatus.setText("Requestor Status");

        lbProcurementStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbProcurementStatus.setText("Pending...");

        lbFinanceStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbFinanceStatus.setText("Pending...");

        lbTrackingTitle.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        lbTrackingTitle.setText("Progress Tracking");

        lbRequestorName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbRequestorName.setText("Requestor");

        lbProcurementName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbProcurementName.setText("Procurement");

        lbFinanceName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lbFinanceName.setText("Finance");

        btnBack.setText("<<Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbRequestorName)
                                    .addComponent(lbProcurementName)
                                    .addComponent(lbFinanceName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 416, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbRequestorStatus)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lbFinanceStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbProcurementStatus, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(120, 120, 120))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lbTrackingTitle)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbRFQId)
                                            .addComponent(lbQuotationId))
                                        .addGap(320, 320, 320))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbPrice)
                                        .addGap(324, 324, 324)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbRemarks)
                                    .addComponent(lbTerms, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnBack)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuotationId)
                    .addComponent(lbTerms))
                .addGap(18, 18, 18)
                .addComponent(lbRFQId)
                .addGap(18, 18, 18)
                .addComponent(lbPrice)
                .addGap(41, 41, 41)
                .addComponent(lbRemarks)
                .addGap(52, 52, 52)
                .addComponent(lbTrackingTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRequestorName)
                    .addComponent(lbRequestorStatus))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProcurementName)
                    .addComponent(lbProcurementStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFinanceName)
                    .addComponent(lbFinanceStatus))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbFinanceName;
    private javax.swing.JLabel lbFinanceStatus;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbProcurementName;
    private javax.swing.JLabel lbProcurementStatus;
    private javax.swing.JLabel lbQuotationId;
    private javax.swing.JLabel lbRFQId;
    private javax.swing.JLabel lbRemarks;
    private javax.swing.JLabel lbRequestorName;
    private javax.swing.JLabel lbRequestorStatus;
    private javax.swing.JLabel lbTerms;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTrackingTitle;
    // End of variables declaration//GEN-END:variables
}
