package view.quotation;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import common.AppContext;
import common.Result;
import controller.procurement.ProcurementController;
import interfaces.IDataRefreshCallback;
import interfaces.IDataRefreshCallbackAware;
import model.quotation.Quotation;
import model.quotation.RFQ;
import enums.RFQStatus;
import enums.RequestStatus;

import java.util.List;
import java.util.stream.Collectors;

import util.NavigationUtil;
import util.UIUtil;

/**
 *
 * @author tisaac
 */
public class QuotationReviewPanel extends javax.swing.JPanel implements IDataRefreshCallbackAware, IDataRefreshCallback {

    private List<RFQ> rfqList;
    private IDataRefreshCallback callback;

    /**
     * Creates new form FinancePanel
     */
    public QuotationReviewPanel() {
        initComponents();
        this.rfqList = AppContext.getNetwork().getRfqDirectory().getRFQList();
        setupListener();
        initUI();

    }

    private void initUI() {
        UIUtil.setEnterpriseTitle(lbTitle, AppContext.getUserEnterprise().getName());
        refreshQuotationTable();
        UIUtil.clearTextComponents(txtRemark);
    }

    private void setupListener() {
        btnBack.addActionListener(e -> handleBack());
        btnView.addActionListener(e -> handleView());
        btnApprove.addActionListener(e -> handleApprove());
        btnReject.addActionListener(e -> handleReject());
    }

    private void handleApprove() {
        Quotation selectedQ = getSelectedQuotation();
        if (selectedQ == null) {
            return;
        }

        Result<Void> r = ProcurementController.getInstance().handleQuotationAccept(selectedQ, txtRemark.getText());
        if (!r.isSuccess()) {
            UIUtil.showError(this, r.getMessage());
            return;
        }
        UIUtil.showInfo(this, r.getMessage());
        refreshQuotationTable();
        UIUtil.clearTextComponents(txtRemark);
    }

    private void handleReject() {
        Quotation selectedQ = getSelectedQuotation();
        if (selectedQ == null) {
            return;
        }

        Result<Void> r = ProcurementController.getInstance().handleQuotationReject(selectedQ, txtRemark.getText());
        if (!r.isSuccess()) {
            UIUtil.showError(this, r.getMessage());
            return;
        }
        UIUtil.showInfo(this, r.getMessage());
        refreshQuotationTable();
        UIUtil.clearTextComponents(txtRemark);
    }

    private void handleBack() {
        NavigationUtil.getInstance().goBack();
        callback.refreshData();
    }

    private void handleView() {
        Quotation selectedQ = getSelectedQuotation();
        if (selectedQ == null) {
            return;
        }

        NavigationUtil.getInstance().showCard(
                new QuotationViewDetailPanel(selectedQ),
                "Quotation View Detail"
        );
    }

    private Quotation getSelectedQuotation() {
        return UIUtil.getSelectedTableObject(
                tblQuotation,
                0,
                Quotation.class,
                this,
                "Please select a quotation"
        ).orElse(null);
    }

    // Only show quotation with status RECEIVED
    private void refreshQuotationTable() {
        List<Quotation> quotations = rfqList.stream()
                .flatMap(rfq -> rfq.getQuotations().getQuotationList().stream())
                .filter(q -> q.getStatus() == RequestStatus.RECEIVED)
                .collect(Collectors.toList());

        UIUtil.reloadTable(tblQuotation,
                quotations,
                e -> new Object[]{
                        e,
                        e.getVendor(),
                        e.getPrice()
                }
        );
    }

    @Override
    public void setCallback(IDataRefreshCallback callback) {
        this.callback = callback;
    }

    @Override
    public void refreshData() {
        refreshQuotationTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblQuotation = new javax.swing.JTable();
        lbTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRemark = new javax.swing.JTextArea();
        btnReject = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        lbTitle1 = new javax.swing.JLabel();

        tblQuotation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Vendor", "Total Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblQuotation);

        lbTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Quotation Budget Approve");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        txtRemark.setColumns(20);
        txtRemark.setRows(5);
        jScrollPane2.setViewportView(txtRemark);

        btnReject.setBackground(new java.awt.Color(255, 0, 0));
        btnReject.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        btnApprove.setBackground(new java.awt.Color(0, 204, 51));
        btnApprove.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        lbTitle1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lbTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle1.setText("Remark:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnBack)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(322, 322, 322)
                                    .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
    }//GEN-LAST:event_btnApproveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTitle1;
    private javax.swing.JTable tblQuotation;
    private javax.swing.JTextArea txtRemark;
    // End of variables declaration//GEN-END:variables
}
