/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.purchaseOrder;

import common.AppContext;
import common.NetworkManager;
import directory.PurchaseOrderDirectory;
import directory.QuotationDirectory;
import directory.RFQDirectory;
import enums.EnterpriseType;
import model.procurement.PurchaseOrder;
import model.quotation.RFQ;
import util.UIUtil;

import java.util.List;
import java.util.stream.Collectors;

/**
 *
 * @author tisaac
 */
public class SubmitPurchaseOrderPanel extends javax.swing.JPanel {

    private RFQDirectory rfq;
    /**
     * Creates new form SubmitPurchaseOrderPanel
     */
    public SubmitPurchaseOrderPanel() {
        initComponents();
        AppContext.getNetwork().getRfqDirectory();

        initUI();
    }

    private void initUI() {
        UIUtil.setEnterpriseTitle(lbTitle, AppContext.getUser().getEnterprise().getName());
    }

    private void setupListeners() {
        btnCreatePO.addActionListener(e -> handleCreatePObtn());
        tblRFQ.getSelectionModel().addListSelectionListener(n -> {
            if (!n.getValueIsAdjusting()) {
                refreshPOTable();
            }
        });
    }

    private void handleCreatePObtn() {}

    private void refreshRFQTable() {
        UIUtil.reloadTable(
                tblRFQ,
                rfq.getRFQList(),
                e -> new Object[]{
                        e,
                        e.getVendor(),
                        e.getDeadline(),
                        e.getStatus()
                }
        );
    }

    private RFQ getSelectedRFQ() {
        return UIUtil.getSelectedTableObject(
                tblRFQ,
                0,
                RFQ.class,
                this,
                "Please select a RFQ to create a Purchase Order."
        ).stream().findFirst().orElse(null);
    }

    // Show PO that has the same quotationId as RFQ and the status is "Completed"
    private void refreshPOTable() {
        List<PurchaseOrder> poList = AppContext.getUserEnterprise().getPurchaseOrderList().getPurchaseOrderList();
        String rfqQuotationId;

        QuotationDirectory qDir = UIUtil.getSelectedTableObject(
                tblRFQ,
                0,
                RFQ.class,
                this,
                "Please select a RFQ to create a Purchase Order."
        ).stream()
                .findFirst()
                .map(rfq -> rfq.getQuotations())
                .orElse(null);

        rfqQuotationId = qDir.findCompletedQuotationByDir();
        //
        poList.removeIf(po -> !po.getQuotationId().equals(rfqQuotationId));

        UIUtil.reloadTable(
                tblPO,
                poList,
                o -> new Object[]{
                        o,
                        o.getVendor(),
                        o.getTotalAmount()
                }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRFQ = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPO = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCreatePO = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        lbTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Submit Purchase Order");

        tblRFQ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Vendor", "Deadline", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRFQ);

        tblPO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Vendor", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblPO);
        if (tblPO.getColumnModel().getColumnCount() > 0) {
            tblPO.getColumnModel().getColumn(0).setResizable(false);
            tblPO.getColumnModel().getColumn(1).setResizable(false);
            tblPO.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel1.setText("RFQ List");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel2.setText("PO List");

        btnCreatePO.setText("Create Purchase Order");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("Only work when at least one of Quotation under RFQ status is Complete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCreatePO)
                .addGap(367, 367, 367))
            .addGroup(layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreatePO)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTable tblPO;
    private javax.swing.JTable tblRFQ;
    // End of variables declaration//GEN-END:variables
}
